name: .NET

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    env:
      ProjectName: BehringerXTouchExtender

    runs-on: windows-latest

    steps:
    - name: Clone
      uses: actions/checkout@v3
        
    - name: Set up Testspace
      uses: testspace-com/setup-testspace@v1
      with:
        domain: ${{github.repository_owner}}

    - name: Restore
      run: dotnet restore --verbosity normal

    - name: Build
      run: dotnet build --no-restore --configuration Release --verbosity normal

    - name: Test
      run: |
        dotnet test --no-build --verbosity normal --configuration Release --collect:"XPlat Code Coverage" --settings Tests/Tests.runsettings --logger "trx;LogFileName=TestResults.xml"
        mv Tests/TestResults/*/coverage.info Tests/TestResults
      env:
        CORECLR_PROFILER_PATH_32: $env:GITHUB_WORKSPACE\Tests\Vendor\JustMock\32\Telerik.CodeWeaver.Profiler.dll
        CORECLR_PROFILER_PATH_64: $env:GITHUB_WORKSPACE\Tests\Vendor\JustMock\64\Telerik.CodeWeaver.Profiler.dll

    - name: Pack
      run: dotnet pack ${{ env.ProjectName }} --no-build --configuration Release --verbosity normal

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ProjectName }}.nupkg
        path: ${{ env.ProjectName }}/bin/Release/*.*nupkg

    - name: Upload test report
      run: testspace Tests/TestResults/TestResults.xml

    - name: Upload coverage
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: Tests/TestResults/coverage.info